site_name: decore Base | Ui fastly
theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  alternate:
    - name: Deutsch
      link: /de/
      lang: de
    - name: English
      link: /en/
      lang: en
plugins:
  - search
  - translate:
      source_lang: de
      languages:
        - en-us
        - es
        - it
        - ru
        - fr
  - mkdocstrings:
      handlers:
        python:
          paths: [../Decore_base/decore_base]
          options:
            show_root_heading: true
            show_bases: false
            show_source: false
  - blog:
      authors: true
      post_url_date_format: "yyyy"
      post_url_format: "{date}/{file}"
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
nav:
  - index.md
  - test.md
  - Dokumentation:
    - doc/index.md
    - doc/fields.md
  - Blog:
    - blog/index.md