site_name: decore Base | Ui fastly
site_url: https://kemopanzah.github.io/decore_Page #DOC - wichtig für Build und GH-Deploy sonst keine korrekten Canonicals und Sitemaps
theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - langly:
      source:
          name: Deutsch
          lang: de
      targets:
        - name: English
          lang: en-us
        - name: Français
          lang: fr
        - name: Español
          lang: es
        - name: Italiano
          lang: it
        - name: Русский
          lang: ru
  - mkdocstrings:
      handlers:
        python:
          paths: [../Decore_base/decore_base]
          options:
            show_root_heading: true
            show_bases: false
            show_source: false
  - blog:
      authors: true
      post_url_date_format: 'yyyy'
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
nav:
  - index.md
  - test.md
  - '[[Dokumentation]]':
    - doc/index.md
    - doc/fields.md
  - '[[Unterprojekte]]':
    - sub/index.md
    - sub/mkdocs_material_langly.md
  - Blog:
    - blog/index.md