site_name: decore.Dev
site_url: https://www.decore.dev #DOC - wichtig für Build und GH-Deploy sonst keine korrekten Canonicals und Sitemaps
extra_css:
    - static/css/custom.css
theme:
  name: material
  logo: static/logo.png
  favicon: static/favicon.ico
  font:
    text: Poppins
  features:
    - content.code.copy
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - langly:
      source:
          name: Deutsch
          lang: de
      targets:
        - name: English
          lang: en-us
  - mkdocstrings:
      handlers:
        python:
          paths: [../Decore_base/decore_base]
          options:
            show_root_heading: true
            show_bases: true
            show_source: false
            members_order: source
  - blog:
      authors: true
      post_url_date_format: 'yyyy'
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - index.md
  - '[[Dokumentation]]':
    - doc/decore.md
    - doc/fields.md
  - '[[Unterprojekte]]':
    - sub/mkdocs_material_langly.md
  - Blog:
    - blog/index.md